apiVersion: v1
kind: Pod
metadata:
  name: demo-maven-github
  labels:
    role: webapp
spec:
  containers:
    - name: web
      image: emdadripon/maven-java-app
      ports:
        - containerPort: 80
          name: web
          protocol: TCP